parameters:
  - name : VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger:
- none

pr:
- none

variables:
  - group: ${{ parameters.VarGroup }}
  - name: ServerParkName
    value: gusty
  - name: SurveyType
    value: OPN
  - name: PackageExtension
    value: zip
  - name: TempPath
    value: c:\blaise\temp\datadelivery\opn

stages:
 - stage: DataDelivery
   displayName: Opn Data Delivery
   jobs:
     - deployment: OpnDeliveryData
       environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: restapitests
       strategy:
        runOnce:
          deploy: 
           steps:
             - checkout: self
             
             - task: DownloadSecureFile@1
               displayName: 'Download GCP Key'
               name: gcpkey
               inputs:
                  secureFile: 'ons-blaise-v2-shared-221e50eb36c7.json'

             - task: PowerShell@2
               displayName: Download SPSS Manipula Package
               inputs:
                targetType: 'inline'
                script: |
                  Write-Host "Login to GCP"
                      gcloud auth activate-service-account $env:ENV_SHARED_SERVICE_ACCOUNT --key-file=$(gcpkey.secureFilePath)
                      
                      Write-Host "Downloading instrument"
                      gsutil cp gs://$env:ENV_SHARED_BUCKET/SpssPackage.zip $env:TempPath\SpssPackage.zip

                        Write-Host "GCP Login with compute service account"
                        gcloud auth login $env:ENV_VM_SERVICEACCOUNT

             - task: PowerShell@2
               displayName: Deliver OPN Instruments
               inputs:
                filePath: '$(Agent.BuildDirectory)/s/scripts/opn/DeliverOpnInstruments.ps1'

             - task: PowerShell@2
               displayName: Clean up temp folders
               inputs:
                targetType: 'inline'
                script: |
                  Remove-Item -Recurse -Force $env:TempPath
